### ISSUE TITLE
About resizing videos

### ISSUE THREAD

**Issue by mbwgh** [xeger/quill-image#15] opened 2022-09-27 15:49 UTC
Hi,

first of all, thanks for creating this project :)

In the package description it says *"Allows user manipulation of width, height and float for images and videos embedded in Quill deltas"*.
An indeed, in the code there is something going on with an `IFrameVideoSpec` which according to #8 could maybe be used to change handler behavior if necessary.

But the intended default behavior is not obvious to me, should Videos be resizable out-of-the-box or not?

I was able to get image resizing to work just fine, but resize handles do not appear for embedded videos (which do show up in the quill delta).

**Comment by xeger** [comment] 2022-09-27 23:49
Hmm. I'll confess that I haven't used videos at all before.

From reading the inherited source code, it looks like the original author intended for videos not to be resizable, as they're marked "unclickable":
https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/specs/IframeVideoSpec.ts#L4

When a video is represented as an `iframe` tag, trying to use the existing code (for resize handles) may not be practical. Furthermore, I'm not sure that reconfiguring the module is sufficient; looks like some code changes would be required even to _try_ to make iframes have an `onclick` ... and I suspct that the click events would go "into" the iframe vs. being passed to the module.

It should be relatively easy to do a quick experiment, if you clone this repo and modify `IframeVideoSpec` to inherit `BlotSpec` and not `UnclickableBlotSpec`. Then you could build the sources and load the local sandbox HTML to see what happens. I'm not expecting anything good, but you might be pleasantly surprised.

**Comment by mbwgh** [comment] 2022-09-28 10:24
Indeed, the behavior becomes messy at least with this simple change.
While resizing seems to work initially, things quickly break when you click on different elements or the float buttons.

![image](https://user-images.githubusercontent.com/28275377/192753512-86527099-8d11-4edd-a997-6a0be6f4f2fd.png)

I am also not really sure what the intended behavior would ideally be. Clicking on the video should of course play it and not just make the resize/float handles visible (as it is now). But then the latter elements should maybe appear on-hover instead of on-click?

I am not sure if that would be an easy change, but I can see this being useful even for images, because I have seen the resize overlay "stick around" in my own app even after the surrounding editor was moved/hidden for example. But this could just as well be an XY problem and there is a better way of preventing this.

**Comment by xeger** [comment] 2022-09-29 19:50
Interesting feedback re resize overlay and sticking around. This has been a chronic problem for me too, in the upstream versions of this module. I recently added [something to help](https://github.com/xeger/quill-image/blob/main/packages/quill-image-actions/src/ImageActions.ts#L43) but it is definitely not perfect.

I think, to make video resize work well, we'd need to redefine how Quill handles videos -- e.g. as an `object` element, not an iframe -- and although that's technically possible, things could get pretty messy (and we'd still need to worry about intercepting clicks meant for the video playback UI).

I think I'm happy closing this issue as "too hard for my puny brain," but I'll leave it open if you think that you or others might attempt a fix.

**Comment by mbwgh** [comment] 2022-10-04 09:34
I have resorted to simply removing the "embed video" button, since it was not important for me anyways, at least not important enough to warrant further investigation.

Regarding the overlay sticking around, I will need to work my way around that, but it remains to be seen whether the fix needs to go into the plugin or my concrete app.

**Comment by xeger** [comment] 2022-10-12 17:18
Sounds good. If you manage to find a reproducible case of the sticky overlay (e.g. in tests or in sandbox), I'll be happy to take a look.

**Closed as completed** 2022-10-12 17:18 UTC
